name: Build python virtual env

on:
  push:
    tags:
      - v*
jobs:
  build:
    strategy:
      matrix:
        python_version: ['3.11']
    runs-on: ubuntu-22.04
    steps:
      - name: Install required libraries
        run: sudo apt install -y libsystemd-dev
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV &&
          echo "PKG_NAME=`basename $GITHUB_REPOSITORY -private`" >> $GITHUB_ENV
      - name: Build venv package
        uses: minvws/action-python-venv-package@v1
        with:
          python_version: ${{ matrix.python_version }}
          package_file_name: ${{ env.PKG_NAME }}
