name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Create version.json
        run: |
          echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > rdo-journalert-private/version.json
      - name: Create tar
        run: tar -czf rdo-journalert-private_${{ env.RELEASE_VERSION }}.tar.gz rdo-journalert-private
      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: rdo-journalert-private_${{ env.RELEASE_VERSION }}
          path: rdo-journalert-private_${{ env.RELEASE_VERSION }}.tar.gz